//! Unsafe Rust bindings to the Przetak C library.
//!
//! This crate provides low-level FFI bindings generated by [`bindgen`](https://github.com/rust-lang/rust-bindgen)
//! from the Przetak C header. It is not intended to be used directly;
//! use the [`przetak`](../przetak/) crate for a safe interface.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

pub mod types;

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
